<a href="https://colab.research.google.com/github/Blutronics/BakeryAssociationRule/blob/main/tensorflowIntro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [ ]:
# Define sequential model with 3 layers
model = keras.Sequential(
    [
     layers.Dense(2,activation ="relu", name = "layer1"),
     layers.Dense(3,activation ="relu", name = "layer2"),
     layers.Dense(4, name = "layer3"),
    ]
)

In [ ]:
x = tf.ones((3,3))

In [ ]:
type(x)

tensorflow.python.framework.ops.EagerTensor

In [ ]:
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
x.ndim

2

In [ ]:
y = model(x)

In [ ]:
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-2.114327  ,  1.3584019 ,  1.2203602 , -0.00904576],
       [-2.114327  ,  1.3584019 ,  1.2203602 , -0.00904576],
       [-2.114327  ,  1.3584019 ,  1.2203602 , -0.00904576]],
      dtype=float32)>

In [ ]:
y.ndim

2

In [ ]:
layer1 = layers.Dense(2,activation ="relu", name = "layer1")
layer2 = layers.Dense(3,activation ="relu", name = "layer2")
layer3 = layers.Dense(4, name = "layer3")

x = tf.ones((3,3))
y = layer3(layer2(layer1(x)))

In [ ]:
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
model = keras.Sequential()
model.add(layers.Dense(2, activation ="relu"))
model.add(layers.Dense(3,activation ="relu"))
model.add(layers.Dense(4))

In [ ]:
model.layers

In [ ]:
model.pop()
print(len(model.layers))

2


In [ ]:
#
layer = layers.Dense(3)
layer.weights #empty

[]

In [ ]:
l = layers.Dense(2, activation ="relu")
l.weights

[]

In [ ]:
t = tf.ones((1,4))
t

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[1., 1., 1., 1.]], dtype=float32)>

In [ ]:
x = tf.ones((1,4))

In [ ]:
y = layer(x)

In [ ]:
layer.weights

[<tf.Variable 'dense_3/kernel:0' shape=(4, 3) dtype=float32, numpy=
 array([[-0.11847013,  0.00640303, -0.05537325],
        [-0.8977535 ,  0.92298305,  0.80746233],
        [-0.07148784,  0.09053993, -0.228629  ],
        [-0.06516737, -0.6941335 , -0.65509605]], dtype=float32)>,
 <tf.Variable 'dense_3/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]